apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-evolution-api-instances
  namespace: evolution-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
